version : '3'
services :
  postgres :
    image : "postgres:13.13"
    container_name : kvmix-postgres
    restart : unless-stopped
    ports :
      - "5432:5432"
    environment :
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=svc_testing_db