spring :
  application :
    name : kvmix
  liquibase :
    change-log :  db/changelog/changelog.xml
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    url : ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/svc_testing_db}
    username : ${DATASOURCE_USERNAME:postgres}
    password : ${DATASOURCE_PASSWORD:postgres}
    driver-class-name : ${DATASOURCE_DRIVER:org.postgresql.Driver}
    hikari :
      pool-name : Hikari
      auto-commit : false
  jpa :
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy : org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view : true
    properties :
      hibernate.jdbc.time_zone : UTC
      hibernate.id.new_generator_mappings : true
      hibernate.connection.provider_disables_autocommit : true
      hibernate.cache.use_second_level_cache : true
      hibernate.cache.use_query_cache : true
      hibernate.generate_statistics : false
      # modify batch size as necessary
      hibernate.jdbc.batch_size : 25
      hibernate.order_inserts : true
      hibernate.order_updates : true
      hibernate.query.fail_on_pagination_over_collection_fetch : true
      hibernate.query.in_clause_parameter_padding : true
    show-sql : false
